---
- name: Create prometheus system group
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    system: true
    state: present

- name: Create prometheus system user
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ prometheus_group }}"
    createhome: false
    home: "{{ prometheus_db_dir }}"

- name: Create prometheus data directory
  ansible.builtin.file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755

- name: Create prometheus configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ prometheus_group }}"
    mode: 0770
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"

- name: Download prometheus binary
  ansible.builtin.get_url:
    url: "{{ prometheus_binary_url }}"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    mode: 0644
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2

- name: Unpack prometheus binaries
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    remote_src: true

- name: Propagate official prometheus and promtool binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_binary_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
    remote_src: true
  with_items:
    - prometheus
    - promtool
  notify:
    - restart prometheus

- name: Propagate official console templates
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: 0644
    owner: root
    group: root
    remote_src: true
  with_items:
    - console_libraries
    - consoles
  notify:
    - restart prometheus
