---
prometheus_version: 2.48.0

prometheus_user: prometheus
prometheus_group: prometheus
prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus
prometheus_binary_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
prometheus_binary_install_dir: /usr/local/bin
prometheus_config_file: prometheus.yml

prometheus_storage_retention: "30d"
prometheus_storage_retention_size: "0"

prometheus_web_listen_address: "127.0.0.1:9090"
prometheus_web_external_url: ""
prometheus_metrics_path: "/{{ (prometheus_web_external_url + '/metrics') | regex_replace('^(.*://)?(.*?)/') }}"

prometheus_config_flags_extra: {}
# prometheus_config_flags_extra:
#   storage.tsdb.retention: 15d
#   alertmanager.timeout: 10s

prometheus_read_only_dirs: []

prometheus_stop_timeout: "600s"

prometheus_global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

prometheus_external_labels:
  environment: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"

prometheus_targets:
  node:
    - targets:
        - localhost:9100
      labels:
#        env: test

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"

# See https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md
prometheus_web_config:
  tls_server_config: {}
  http_server_config: {}
  basic_auth_users: {}
