---
- include_tasks: install.yml

- include_tasks: configure.yml

- name: Start Fluentbit service
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ fluentbit_package_name }}"
    state: started
